### ISSUE TITLE
Timeline: popups in comments editor are cut-off

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1454]
https://una.io/page/view-discussion?id=1065
https://una.io/page/view-discussion?id=1083
It can be fixed using the following way but with standard classes/styles, or maybe there is better way..

```css
div.bx-tl-view div.bx-tl-item .bx-tl-item-cnt {
    /* overflow: hidden; */
}
.bx-tl-view div.bx-tl-item div.bx-tl-item-comments-holder {
    border-bottom-right-radius: .625rem;
    border-bottom-left-radius: .625rem;
}
```
