### ISSUE TITLE
Timeline: twitter embeds are out of screen on mobiles

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1995]
![570323d3fa3bc9b3ea40863f11350a4b](https://user-images.githubusercontent.com/3324866/53722178-0da06c80-3eb9-11e9-8d83-ebf83650c0ab.jpg)
 It looks like the following CSS fixes it:
```css
div.bx-tl-view-outline div.bx-tl-il-embed .embedly-card-hug iframe, 
div.bx-tl-view-timeline div.bx-tl-il-embed .embedly-card-hug iframe  {
width:600px;
}
```
or maybe just remove: `width:100%;` if it doesn't affect anything.
