### ISSUE TITLE
Froala: RTL support

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2263]
https://una.io/page/view-discussion?id=3492

**Comment by AlexTr** [comment]
There is a bug in Froala themes which can be fixed using the following styles:
```css
html .gray-theme.fr-box.fr-basic .fr-element  {
    text-align:start;
}
```
