### ISSUE TITLE
Too small bottom margin for the custom menu icons

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#2864]
The trouble has been described here
https://una.io/page/view-discussion?id=5908

The reason: the CSS menu class

```css
.bx-menu-floating-blocks li img, .bx-menu-floating-blocks-wide li img {
margin: 1rem 1.5rem .2rem 1.5rem;
}
```

has too small value in the selected part.
change to:

```css
.bx-menu-floating-blocks li img, .bx-menu-floating-blocks-wide li img {
margin: 1rem 1.5rem .5rem 1.5rem;
}
```
