### ISSUE TITLE
Resize background images in floating blocks menu by default

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#462]
Like this:

``` css
.bx-menu-floating-blocks li img, 
.bx-menu-floating-blocks li .sys-icon {
    background-size:2rem 2rem;
}
```
